### ISSUE TITLE
A problem about how to produce time series image（undersampled images）

### ISSUE THREAD

**Issue by bruceandbruce** [bigponglee/SL-SP-MRF#2]
Hi,Mr Li.I learned from your homepage that you have some research achievements in magnetic resonance fingerprint imaging. I have just started entering this industry and currently have many doubts and difficulties. Firstly, I have been trying to learn the most classic MRF framework recently, but I don't know how to simulate it, especially how to use spiral sampling to obtain undersampled images. Do you have any code available in this area.

**Comment by bigponglee** [comment]
I recommend checking out the work by Yonina Eldar's group at the Weizmann Institute of Science. They have developed a comprehensive software package called "FLOR" for magnetic resonance fingerprinting with low-rank modeling. You can find more details and the code on their website: https://www.weizmann.ac.il/math/yonina/software-hardware/software/flor-magnetic-resonance-fingerprinting-low-rank

**Comment by bigponglee** [comment]
> Hi,Mr Li.I learned from your homepage that you have some research achievements in magnetic resonance fingerprint imaging. I have just started entering this industry and currently have many doubts and difficulties. Firstly, I have been trying to learn the most classic MRF framework recently, but I don't know how to simulate it, especially how to use spiral sampling to obtain undersampled images. Do you have any code available in this area.

I recommend checking out the work by Yonina Eldar's group at the Weizmann Institute of Science. They have developed a comprehensive software package called "FLOR" for magnetic resonance fingerprinting with low-rank modeling. You can find more details and the code on their website: https://www.weizmann.ac.il/math/yonina/software-hardware/software/flor-magnetic-resonance-fingerprinting-low-rank

**Comment by bruceandbruce** [comment]
Thanks
&nbsp;


王金蹊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peng ***@***.***&gt;; 
发送时间: 2023年12月6日(星期三) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bigponglee/SL-SP-MRF] A problem about how to produce time series image（undersampled images） (Issue #2)





  
Hi,Mr Li.I learned from your homepage that you have some research achievements in magnetic resonance fingerprint imaging. I have just started entering this industry and currently have many doubts and difficulties. Firstly, I have been trying to learn the most classic MRF framework recently, but I don't know how to simulate it, especially how to use spiral sampling to obtain undersampled images. Do you have any code available in this area.
  
I recommend checking out the work by Yonina Eldar's group at the Weizmann Institute of Science. They have developed a comprehensive software package called "FLOR" for magnetic resonance fingerprinting with low-rank modeling. You can find more details and the code on their website: https://www.weizmann.ac.il/math/yonina/software-hardware/software/flor-magnetic-resonance-fingerprinting-low-rank
